/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.91
 * Generated at: 2024-08-12 08:36:49 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class CreateEmp_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"./style0.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"./style2.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<h1 style=\"text-align:center\">Employee Form</h1>\r\n");
      out.write("	<div class=\"formContainer\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("		<form action=\"insert\" method=\"post\">\r\n");
      out.write("				<div class=\"fieldset\">\r\n");
      out.write("                      <label>id  </label>\r\n");
      out.write("                      <label>:</label>\r\n");
      out.write("                      <input\r\n");
      out.write("                        type=\"number\"\r\n");
      out.write("                        name=\"id\"\r\n");
      out.write("                        min=\"0\"\r\n");
      out.write("                        placeholder=\"Enter User id\" required>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"fieldset\">\r\n");
      out.write("                      <label>Name  </label>\r\n");
      out.write("                      <label>:</label>\r\n");
      out.write("                      <input\r\n");
      out.write("                        type=\"text\"\r\n");
      out.write("                        name=\"name\"\r\n");
      out.write("                        placeholder=\"Enter User Name\" required>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <div class=\"fieldset\">\r\n");
      out.write("                      <label>Dept.id  </label>\r\n");
      out.write("                      <label>:</label>\r\n");
      out.write("                      <input\r\n");
      out.write("                        type=\"number\"\r\n");
      out.write("                        name=\"deptid\"\r\n");
      out.write("                        min=\"0\"\r\n");
      out.write("                    \r\n");
      out.write("                        placeholder=\"Enter Dept id\" required>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"fieldset\">\r\n");
      out.write("                      <label>salary </label>\r\n");
      out.write("                      <label>:</label>\r\n");
      out.write("                      <input\r\n");
      out.write("                        type=\"text\"\r\n");
      out.write("                        name=\"sal\"\r\n");
      out.write("                        placeholder=\"Enter User Salary\" required>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"fieldset\">\r\n");
      out.write("                      <label>Email  </label>\r\n");
      out.write("                      <label>:</label>\r\n");
      out.write("                      <input\r\n");
      out.write("                        type=\"email\"\r\n");
      out.write("                        name=\"email\"\r\n");
      out.write("                        placeholder=\"Enter User Email\" required>\r\n");
      out.write("                    </div>\r\n");
      out.write("				<div class=\"fieldset\">\r\n");
      out.write("                      <label>Password  </label>\r\n");
      out.write("                      <label>:</label>\r\n");
      out.write("                      <input\r\n");
      out.write("                        type=\"password\"\r\n");
      out.write("                        name=\"pass\"\r\n");
      out.write("                        placeholder=\"Enter User password\" required>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"fieldset\">\r\n");
      out.write("                      <label>Confirm Password  </label>\r\n");
      out.write("                      <label>:</label>\r\n");
      out.write("                      <input\r\n");
      out.write("                        type=\"text\"\r\n");
      out.write("                        name=\"passw\"\r\n");
      out.write("                        placeholder=\"Enter Confirm Password\" required>\r\n");
      out.write("            \r\n");
      out.write("                </div>\r\n");
      out.write("                    <input type=\"submit\" value=\"Register\" />\r\n");
      out.write("            </form>\r\n");
      out.write("            </div>\r\n");
      out.write("	</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
